import BrandLogo from '@/components/BrandLogo'
import { Icon, type IconName } from '@/components/icons'

const FEATURES: readonly [string, string, IconName, string, string][] = [
  ['Знайди свою компанію', 'Обирай людей і зустрічі за віком, гендером, інтересами та відстанню.', 'search', 'from-[#eee7fa]/95 to-[#ddd0f3]/90', '5 км від тебе'],
  ['Створюй власні зустрічі', 'Кава, прогулянка, концерт, спорт, бар або будь-яка інша активність.', 'calendar', 'from-[#fff0e6]/95 to-[#f6d6c5]/90', 'Будь-яка ідея'],
  ['Вирішуй, хто долучиться', 'Вільний вхід, участь після підтвердження або приватна зустріч за запрошенням.', 'userCheck', 'from-[#e8f5ef]/95 to-[#cae7dc]/90', 'Твій вибір'],
  ['Ходи разом на події', 'Збирай компанію на концерти, кіно, фестивалі та інші заходи. За потреби використовуй «Банку на захід».', 'music', 'from-[#f8e8f0]/95 to-[#ebcfdf]/90', 'Разом цікавіше'],
]

const FEATURE_LAYOUT = ['lg:col-span-7', 'lg:col-span-5', 'lg:col-span-5', 'lg:col-span-7'] as const

const STEPS: readonly [string, IconName][] = [['Обери, що тобі цікаво', 'sparkles'], ['Знайди людей або подію поруч', 'search'], ['Долучись', 'plus'], ['Зустріньтесь наживо', 'users']]

const EXAMPLES = [
  ['«Хочу сьогодні на каву»', 'Знайди компанію поруч', 'poruch-coffee.jpg', 'Друзі спілкуються за кавою'],
  ['«Йду на концерт»', 'Створи збір і знайди людей', 'poruch-concert.jpg', 'Люди разом на концерті'],
  ['«Хочу познайомитися»', 'Обери вік, гендер та інтереси', 'poruch-walk.jpg', 'Компанія друзів гуляє містом'],
  ['«Створив зустріч»', 'Сам вирішуй, кого підтвердити', 'poruch-friends.jpg', 'Друзі проводять час разом'],
] as const

const landingImage = (name: string) => `${import.meta.env.BASE_URL}images/landing/${name}`

export default function LandingPage({ onStart, onGoogleSignIn, error }: { onStart: () => void; onGoogleSignIn: () => void; error?: string | null }) {
  return (
    <div className="relative min-h-[100dvh] overflow-x-hidden bg-transparent text-brand-ink">
      <header className="relative mx-auto flex w-full max-w-6xl items-center justify-between gap-3 px-4 py-5 sm:px-6"><BrandLogo className="w-32 sm:w-40" /><div className="flex items-center gap-2"><button type="button" onClick={onGoogleSignIn} className="h-10 rounded-xl border border-brand-border bg-white px-3 text-[10px] font-extrabold text-brand-ink-soft transition hover:border-brand-accent hover:text-brand-accent sm:px-4 sm:text-xs">УВІЙТИ З GOOGLE</button><button type="button" onClick={onStart} className="h-10 rounded-xl bg-brand-accent px-4 text-xs font-extrabold text-white transition hover:bg-brand-accent-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-accent sm:px-5">ПОЧАТИ</button></div></header>{error && <div role="alert" className="relative mx-auto mb-3 w-[calc(100%-2rem)] max-w-6xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 sm:w-[calc(100%-3rem)]">{error}</div>}
      <main className="relative mx-auto w-full max-w-6xl px-4 pb-10 sm:px-6 sm:pb-14">
        <section className="relative overflow-hidden rounded-[30px] border border-white/80 bg-white/70 p-6 shadow-[0_22px_70px_rgba(64,46,96,0.11)] sm:p-10 lg:grid lg:min-h-[540px] lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-8 lg:p-12">
          <div className="relative z-10"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1 text-[10px] font-extrabold text-violet-800">Кава</span><span className="rounded-full border border-rose-200 bg-rose-50 px-3 py-1 text-[10px] font-extrabold text-rose-800">Прогулянки</span><span className="rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-[10px] font-extrabold text-indigo-800">Концерти</span></div><h1 className="mt-5 max-w-xl text-4xl font-black leading-[1.04] tracking-[-0.05em] text-[#17131e] sm:text-5xl lg:text-[54px]">Poruch — миттєві зустрічі зі своїми!</h1><p className="mt-5 max-w-xl text-sm font-semibold leading-6 text-[#3f3949] sm:text-base sm:leading-7">Знаходь компанію за віком, гендером та спільними інтересами. Створюй власні зустрічі або долучайся до подій поруч.</p><button type="button" onClick={onStart} className="mt-7 h-12 rounded-2xl bg-brand-accent px-8 text-sm font-black tracking-wide text-white shadow-[0_10px_24px_rgba(104,80,166,0.3)] transition hover:-translate-y-0.5 hover:bg-brand-accent-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-accent">ПОЧАТИ</button><div className="mt-6 flex flex-wrap gap-2 text-[10px] font-extrabold text-[#5e5669]"><span>5 км від тебе</span><span aria-hidden="true">·</span><span>4 учасники</span><span aria-hidden="true">·</span><span>За підтвердженням</span></div></div>
          <div className="relative mt-9 h-[300px] sm:h-[390px] lg:mt-0 lg:h-[450px]"><div className="absolute -right-12 top-3 h-56 w-56 rounded-full bg-[#e2d7f5] blur-2xl" aria-hidden="true" /><img src={landingImage('poruch-friends-city.jpg')} alt="Компанія друзів зустрілася у місті" fetchPriority="high" className="absolute inset-0 h-full w-full rounded-[28px] object-cover shadow-[0_22px_45px_rgba(44,33,64,0.2)] sm:left-[8%] sm:h-[88%] sm:w-[78%] lg:left-[10%]" /><img src={landingImage('poruch-coffee.jpg')} alt="Двоє людей розмовляють за кавою" className="absolute -bottom-1 -left-2 hidden h-[42%] w-[42%] rotate-[-3deg] rounded-[22px] border-[5px] border-white object-cover shadow-xl sm:block" /><img src={landingImage('poruch-concert.jpg')} alt="Друзі разом слухають живу музику" className="absolute -right-1 bottom-3 hidden h-[37%] w-[38%] rotate-[3deg] rounded-[22px] border-[5px] border-white object-cover shadow-xl sm:block" /></div>
        </section>

        <section className="py-10 sm:py-14"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-brand-accent">Живи не лише онлайн</p><h2 className="mt-2 text-2xl font-black tracking-[-0.03em] text-[#1d1824] sm:text-3xl">Що можна робити в Poruch</h2></div><span className="hidden rotate-2 rounded-full bg-[#e8ddf7] px-4 py-2 text-xs font-extrabold text-[#593ca0] sm:block">Люди поруч →</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-12 lg:gap-4">{FEATURES.map(([title, text, icon, surface, chip], index) => <article key={title} className={`group relative overflow-hidden rounded-[24px] border border-white/80 bg-gradient-to-br p-5 shadow-[0_14px_34px_rgba(43,34,66,0.11)] sm:p-6 ${surface} ${FEATURE_LAYOUT[index]}`}><span className="absolute -right-10 -top-12 h-36 w-36 rounded-[42%_58%_64%_36%] bg-white/35 transition-transform duration-300 group-hover:scale-110" aria-hidden="true" /><span className="absolute -bottom-12 right-[22%] h-24 w-24 rounded-full border-[16px] border-white/20" aria-hidden="true" /><div className="relative flex items-start justify-between gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-[20px_25px_18px_24px] bg-white/85 text-[#5b3e9e] shadow-[0_7px_18px_rgba(70,50,108,0.14)]"><Icon name={icon} className="h-7 w-7" /></span><span className="rounded-full border border-white/70 bg-white/55 px-3 py-1 text-[10px] font-extrabold text-[#534661]">{chip}</span></div><h3 className={`relative mt-5 font-black leading-tight text-[#211b29] ${index === 0 || index === 3 ? 'text-xl' : 'text-lg'}`}>{title}</h3><p className="relative mt-2 max-w-xl text-sm font-semibold leading-6 text-[#4b4353]">{text}</p></article>)}</div></section>

        <section className="relative pb-11 pt-2 sm:pb-14 sm:pt-4"><div className="flex items-center gap-3"><h2 className="text-2xl font-black tracking-[-0.03em] text-[#1d1824] sm:text-3xl">Як це працює</h2><span className="h-px flex-1 bg-gradient-to-r from-[#8568c0]/45 to-transparent" aria-hidden="true" /></div><ol className="relative mt-8 grid gap-7 md:grid-cols-4 md:gap-4"><svg className="pointer-events-none absolute left-[7%] top-4 hidden h-24 w-[86%] overflow-visible md:block" viewBox="0 0 1000 100" preserveAspectRatio="none" aria-hidden="true"><path d="M20 54 C145 4 250 92 377 49 S620 5 754 53 S900 86 980 34" fill="none" stroke="rgba(104,80,166,0.48)" strokeWidth="3" strokeDasharray="5 11" strokeLinecap="round" /></svg><span className="pointer-events-none absolute bottom-8 left-8 top-8 border-l-2 border-dashed border-[#7656bd]/35 md:hidden" aria-hidden="true" />{STEPS.map(([label, icon], index) => <li key={label} className={`relative grid grid-cols-[64px_1fr] items-center gap-4 md:block md:text-center ${index === 1 || index === 3 ? 'md:translate-y-8' : ''}`}><div className="relative z-10 mx-auto"><span className="absolute -left-2 -top-3 z-20 text-xl font-black tracking-[-0.05em] text-[#4f368b]">0{index + 1}</span><span className={`grid h-16 w-16 place-items-center border border-white/80 text-[#5b3e9e] shadow-[0_10px_24px_rgba(70,50,108,0.15)] ${index % 2 ? 'rounded-[40%_60%_42%_58%] bg-[#f9dfd2]' : 'rounded-[58%_42%_60%_40%] bg-[#e3d9f4]'}`}><Icon name={icon} className="h-7 w-7" /></span></div><p className="max-w-[13rem] text-sm font-black leading-5 text-[#302938] md:mx-auto md:mt-4">{label}</p></li>)}</ol></section>

        <section className="py-11 sm:py-16"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-brand-accent">Знайоме відчуття?</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.03em] sm:text-3xl">Сценарії на щодень</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{EXAMPLES.map(([quote, result, image, alt]) => <article key={quote} className="group relative min-h-64 overflow-hidden rounded-[24px] bg-brand-ink shadow-[0_12px_32px_rgba(36,28,48,0.13)]"><img src={landingImage(image)} alt={alt} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-300 group-hover:scale-[1.025]" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-5 text-white sm:p-6"><h3 className="text-xl font-extrabold tracking-[-0.02em]">{quote}</h3><p className="mt-1 text-sm text-white/85">{result}</p></div></article>)}</div></section>

        <section className="relative overflow-hidden rounded-[26px] bg-gradient-to-br from-[#7258ad] via-brand-accent to-[#9a76c1] px-6 py-10 text-center text-white shadow-[0_18px_45px_rgba(91,66,145,0.25)] sm:px-10 sm:py-12"><div className="absolute -left-10 -top-12 h-40 w-40 rounded-full border-[24px] border-white/10" aria-hidden="true" /><div className="absolute -bottom-14 -right-8 h-44 w-44 rounded-full bg-[#f3cdbb]/20 blur-sm" aria-hidden="true" /><div className="absolute inset-0 opacity-15 [background-image:radial-gradient(white_0.6px,transparent_0.6px)] [background-size:13px_13px]" aria-hidden="true" /><div className="relative"><p className="text-xs font-bold uppercase tracking-[0.16em] text-white/75">Кава · прогулянки · концерти · спорт</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em]">Знайди своїх поруч</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-white/80">Обери, що тобі цікаво, і зроби перший крок до реальної зустрічі.</p><button type="button" onClick={onStart} className="mt-6 h-12 rounded-2xl bg-white px-9 text-sm font-extrabold text-brand-accent shadow-lg transition hover:-translate-y-0.5 hover:bg-brand-accent-soft focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">ПОЧАТИ</button></div></section>
      </main>
    </div>
  )
}
